[package]
name = "mandala-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mandala"
path = "src/main.rs"

[dependencies]
mandala-core.workspace = true
mandala-media.workspace = true

anyhow.workspace = true
crossbeam-channel.workspace = true
dirs = "6"
eframe.workspace = true
egui.workspace = true
image.workspace = true
parking_lot.workspace = true
serde.workspace = true

[dev-dependencies]
ron = "0.12"
tempfile = "3"
