[package]
name = "mandala-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mandala"
path = "src/main.rs"

[dependencies]
mandala-core.workspace = true
mandala-media.workspace = true

anyhow.workspace = true
crossbeam-channel.workspace = true
dirs = "6"
eframe.workspace = true
filetime = "0.2"
egui.workspace = true
image.workspace = true
parking_lot.workspace = true
serde.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Globalization"] }

[dev-dependencies]
filetime = "0.2"
ron = "0.12"
tempfile = "3"
